spring:
  application:
    name: avoota_inventory
  datasource:
    url: jdbc:mysql://localhost:3306/avoota
    username: root
    password: Count02
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  address: 0.0.0.0   # 👈 Add this to make the app accessible on LAN

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
