##spring.application.name=avoota_inventory
#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/avoota}
#spring.datasource.username=${DB_USER:root}
#spring.datasource.password=${DB_PASSWORD:Count02}